### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nnecklace** [futurice/clojure-workshop#1]
Figure out what license to use for this.

**Comment by nnecklace** [comment]
GNU v2?

**Comment by nnecklace** [comment]
Maybe we should actually use the Eclipse Public License ?

**Comment by nnecklace** [comment]
Maybe we should use this license that every clojure project seems to use?

**Comment by ykarikos** [comment]
Anything works for me. Personnally, I prefer MIT, but GPLv2 and EPL works as well.

**Comment by nnecklace** [comment]
Let's just go with MIT and Close this issue already
