### ISSUE TITLE
Section 1 - Programming & Using the REPL

### ISSUE THREAD

**Issue by nnecklace** [futurice/clojure-workshop#6]

**Comment by roryhow** [comment]
Is there a legal problem if we created a smaller version of the Clojure Koans repo and get people to clone that? Of course linking to the original repo and giving all credit to the original contributors.

https://github.com/functional-koans/clojure-koans/tree/master/src/koans I can't see us needing to bother with anything from 18 onwards. But most of the ones before that might be handy to go over quickly.

We probably don't need all of the koans for each category as well, so we could just select a few relevant ones from each and roll with those?

We could even have some koans already commented out (to keep the pace), and then if someone manages to finish ahead of time they could go back and uncomment additional ones they would like to do.

This _seems_ to be the easiest way to do this but I'm not particularly clued in on the eclipse license and what that would mean for us in this context.

**Comment by nnecklace** [comment]
Amazing idea! Koans provides a koans engine template for writing your own koans. We could use the template and add our own. Maybe 15 - 20 is enough? I also went through the license, the most interesting part was this section:

>The EPL license is a copyleft license. If you modify an EPL’ed component and distribute it in the source code form as part of your program, you’re required to disclose the modified code under the EPL. If you distribute such a program in its object code form, you’re required to state that the source code can be made available to the recipient upon request. You’re also required to share the method for requesting the source code.

If I understand correctly, we only need to provide a means to share our code, which we already do :)

**Comment by roryhow** [comment]
Have you started work on this @nnecklace? I'd be happy to take the reins on this section and you could start to tackle the backend work if you wanted.

I'll be working my way through the koans on my own and I can just select the ones that I feel gather the  sentiment accurately enough for that section, then I can make a PR to this repo - I'll probably make a new directory `/materials/01_clj_fundamentals/` or something in that realm which will be a seperate lein project with the koans included.

Does that sound good to you? (granted if you haven't started on this already, of course)

**Comment by nnecklace** [comment]
@roryhow  I did start working on this. Haven't made any koans yet. I built a small project with the koans template. I'll push everything I've done so far. Branch is called `section-1`

**Comment by roryhow** [comment]
Ah looks good! Seems we are on the same page there.

I'll work on the koans anyway but seems like you've got section 1 under control :) 

We can pick things up again on Tuesday after we decide for a basic project structure for the backend and frontend

**Comment by nnecklace** [comment]
Feel free to add anything you find relevant to the branch :) This is a team effort after all :)
My plan from the get go was to "copy" Helsinki University's *introduction into programming* course's setup. This is probably the only programming course, that I know of, that has gotten so much praise for begin so detailed and well explained. 

The course is setup in sections, much like our whole workshop. Each section has a set of exercises, i.e *koans* (4 - 8). 

A section could e.g. be conditionals. There's a short description of how conditionals work, and how you write them. After that you do the exercises. 

As I said, feel free to add any koans you think are good. Also if you have any counter points or other ideas, please share :)

**Comment by nnecklace** [comment]
@roryhow I added two small sections to the koans. You seem to have a much clearer vision on the koans and you seemed quite enthusiastic about them, would you like to take over this one, and more koans or any other tasks/challenges for the participants :) ?
